version: 2.1
orbs:
  elixir: membraneframework/elixir@dev:f196d8f4809429df291e0a1634e4b9b870626d8e

workflows:
  precompile:
    jobs:
      - elixir/precompile_for_macos_intel: &parameters
          package-name: fdk-aac
          expected-version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - elixir/precompile_for_macos_arm:
          <<: *parameters
      - elixir/precompile_for_linux:
          <<: *parameters
      - elixir/publish_precompiled:
          requires:
            - elixir/precompile_for_macos_arm
            - elixir/precompile_for_macos_intel
            - elixir/precompile_for_linux
          version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
