version: 2.1
orbs:
  elixir: membraneframework/elixir@dev:f8799b932221fcc9db4a83639fc67d42e850fd21

workflows:
  precompile-publish:
    jobs:
      - elixir/precompile_for_macos_intel:
          package-name: fdk-aac
      - elixir/precompile_for_linux:
          package-name: fdk-aac
      - elixir/publish_precompiled:
          version: version2
          requires:
            - elixir/precompile_for_macos_intel
            - elixir/precompile_for_linux