version: 2.1
orbs:
  elixir: membraneframework/elixir@dev:1bd658cb2d654f7fd09add28c9afa3578b369695

workflows:
  precompile-publish:
    jobs:
      - elixir/precompile_for_macos_intel:
          package-name: fdk-aac
          filters:
            tags: 
              only: /v.*/
      - elixir/precompile_for_linux:
          package-name: fdk-aac
          filters:
            tags: 
              only: /v.*/
      - elixir/publish_precompiled:
          requires:
            - elixir/precompile_for_macos_intel
            - elixir/precompile_for_linux
          version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
