version: 2.1
orbs:
  elixir: membraneframework/elixir@dev:7315159f6714929143049b96a8acb602068da12a

workflows:
  precompile:
    jobs:
      - elixir/precompile_for_macos_intel:
          package-name: fdk-aac
          version: << pipeline.git.tag >> 
          filters:
            tags: 
              only: /v.*/
      - elixir/precompile_for_linux:
          package-name: fdk-aac
          version: << pipeline.git.tag >>
          filters:
            tags: 
              only: /v.*/
      - elixir/publish_precompiled:
          requires:
            - elixir/precompile_for_macos_intel
            - elixir/precompile_for_linux
          version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
