version: 2.1
orbs:
  elixir: membraneframework/elixir@dev:2fd5766cd9f5c06f0d0de791f9ff54bc2205a41f

workflows:
  precompile:
    jobs:
      - elixir/precompile_for_macos_intel: &parameters
          package-name: fdk-aac
          expected-version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - elixir/precompile_for_macos_arm:
          <<: *parameters
      - elixir/precompile_for_linux:
          <<: *parameters
      - elixir/publish_precompiled:
          requires:
            - elixir/precompile_for_macos_arm
            - elixir/precompile_for_macos_intel
            - elixir/precompile_for_linux
          version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
