version: 2.1
orbs:
  elixir: membraneframework/elixir@dev:1b74046e2173a377eb57edb267abc664d3bf9091

workflows:
  precompile:
    jobs:
      - elixir/precompile_for_macos_intel: &parameters
          package-name: fdk-aac
          expected-version: << pipeline.git.tag >> 
          filters:
            tags: 
              only: /v.*/
      - elixir/precompile_for_macos_arm:
          <<: *parameters     
      - elixir/precompile_for_linux:
          <<: *parameters
      - elixir/publish_precompiled:
          requires:
            - elixir/precompile_for_macos_arm
            - elixir/precompile_for_macos_intel
            - elixir/precompile_for_linux
          version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
