version: 2.1
orbs:
  elixir: membraneframework/elixir@dev:b4aaaa1093c69b2dfc5ab958ac4f3c542a77b43d

workflows:
  precompile:
    jobs:
      - elixir/precompile_for_macos_intel:
          package-name: fdk-aac
          expected-version: << pipeline.git.tag >> 
          filters:
            tags: 
              only: /v.*/
      - elixir/precompile_for_linux:
          package-name: fdk-aac
          expected-version: << pipeline.git.tag >>
          filters:
            tags: 
              only: /v.*/
      - elixir/publish_precompiled:
          requires:
            - elixir/precompile_for_macos_intel
            - elixir/precompile_for_linux
          version: << pipeline.git.tag >>
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
